services:

  localstack:
    container_name: localstack
    image: localstack/localstack:3.8.1
    ports:
      - "127.0.0.1:4510-4559:4510-4559"  # external service port range
      - "127.0.0.1:4566:4566"            # LocalStack Edge Proxy
    environment:
      - LOCALSTACK_HOSTNAME=localhost.localstack.cloud  # set this env var to expose localstack to other containers
      - AWS_ACCESS_KEY_ID=key
      - AWS_SECRET_ACCESS_KEY=secret
      - AWS_DEFAULT_REGION=eu-west-1
      - SERVICES=dynamodb,sns,sqs,lambda
      # ---
      - DEBUG=${DEBUG-}
    volumes:
      - "$PWD/tmp/localstack:/var/lib/localstack"
      - "$PWD/dynamodb-lambda-function/shared:/shared"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      default:
        aliases:
          - localhost.localstack.cloud   # set this network aliases to expose localstack to other containers
